spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/chat_user
    username: root
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.gmail.com
    port: 587
    username: shubh9910tiwari@gmail.com
    password: nnyp wmpr trcu abdt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
client:
  url: http://localhost:5173/